### PR TITLE
Implement workload identity

### PR DESCRIPTION
**Pull request by RafikFarhad**
Implementation of #26.
Resolve issue #30.

### CODE REVIEW

**Comment by NextStepGuru** [comment]
@RafikFarhad i'd love to use this PR...any eta to implement it?

**Comment by RafikFarhad** [comment]
Thanks @NextStepGuru, I'll try my best to deliver this by the weekend (23rd Oct).

**Comment by RafikFarhad** [comment]
Thanks, @NextStepGuru, for your generous offer. I have not given a thought about getting any support. You can always support me by giving guidelines to maintain this kind of usable project.

**Comment by RafikFarhad** [comment]
🎉 I am releasing `v5-beta` today. I will monitor this release for some time for any critical issues. And maybe, after getting some adoption and testing from other people, we can release `v5`, 🍻!

**Comment by NextStepGuru** [comment]
@RafikFarhad worked on the first try! Thank-you so much for your help on getting this pushed out.

**Pull request merged**
